### ISSUE TITLE
Connect to Visual Studio Mobile Center

### ISSUE THREAD

**Issue by Saadnajmi** [MSA-Lone-Star-Council/Showdown#17]
Host the app onto (https://www.visualstudio.com/vs/mobile-center/)

This will help with adding beta testers (*COUGH* Lone Star Council *COUGH*) who want to see progress.

**Comment by zuhairp** [comment]
Make sure not to commit any secret information, like API keys!

**Comment by Saadnajmi** [comment]
Any way we can commit that but not make it public? IE what's the best way to share that between us but not the public?

**Comment by zuhairp** [comment]
Simply, you don't commit. I'm doing something similar in the backend. You can read the details in the backend readme, but pretty much you make an example file and commit that and gitignore the real one.

I'm going to look into Xamarin specific solutions. Android Studio has a gradle.priperties file that can be used in a similar way

**Comment by zuhairp** [comment]
I'm going to create a work item for managing secrets. I'll take point on that

**Comment by zuhairp** [comment]
Done as much as it can be for now
